### ISSUE TITLE
Add an endpoint to lookup a user's permissions for a given dataset.

### ISSUE THREAD

**Issue by Foxcapades** [VEuPathDB/service-dataset-access#28]
Needs to check staff/provider/end user tables, and return manager/owner flag for staff and providers.

**Comment by jtlong3rd** [comment]
It's worth noting that the [service spec](https://docs.google.com/document/d/1M_dkJYEdUXCl9Tqgdr3Rd02vWrgjqOV-e3FHNoO03l4/edit#heading=h.m0fyf8j3qfg) also calls for a `/permissions` endpoint which returns all of the user's permissions (not just their permission for a given dataset). This `/permissions` endpoint would be sufficient to address this issue.

Happy to weigh in on the format for the response!
