### ISSUE TITLE
Allow "non-owner staff" to GET lists of all 3 tables; allow "non-manager" providers to GET lists for the dataset-providers and end-users tables

### ISSUE THREAD

**Issue by jtlong3rd** [VEuPathDB/service-dataset-access#37]
More specifically:

* `GET` requests to `/staff` should be permitted for all staff, not just owners

* `GET` requests to `/dataset-providers?datasetId=DATASET_ID` should be permitted for all staff and providers, not just owners and managers

**Comment by Foxcapades** [comment]
Shifted to bug because this was in the amended requirements, but was missed when updating to meet those requirements.
