### ISSUE TITLE
patch on end_users updates the start_date

### ISSUE THREAD

**Issue by aurreco-uga** [VEuPathDB/service-dataset-access#39]
the field showed in UI (we cannot tell what was in the database) : 11 Nov 2020 02:16:37 GMT 
after patching the approval_status and denial_reason (not the date), 
now it contains in the database: 10-NOV-20 12.00.00.000000 AM GMT

**Comment by Foxcapades** [comment]
Added a patch that _should_ fix this with commit https://github.com/VEuPathDB/service-dataset-access/commit/f4efbe78501e60ca885bc0cb4a4060f5933937a0
