### ISSUE TITLE
update permissions endpoint to inform if a request is pending, add a new endpoint to retrieve an access request fields

### ISSUE THREAD

**Issue by aurreco-uga** [VEuPathDB/service-dataset-access#55]
priority set based on client work needed and feature set for 62.. might be negotiable.. 

relates to https://github.com/VEuPathDB/web-eda/issues/1150, points 3 and 4.

(3) use the current endpoint permissions to find out if a user has a pending request to access a study:
( api change to be agreed upon)
/eda/permissions/
{ actionAuthorization: {.....}
requestPending: true
isManager = false
isUserStudy....
.... }

(4) when the user has already submitted a request and the request is pending,
(4.1) use a new endpoint to grab the request content and show the form filled in :
(endpoint to be agreed upon)
/eda/dataset-request-form?datasetId=DS_fe95d702c3

**Comment by ryanrdoherty** [comment]
#3 above is covered by this PR: https://github.com/VEuPathDB/service-dataset-access/pull/56
#4 is already complete.  Client can retrieve a dataset access request's information by dataset ID + user ID using:
https://veupathdb.github.io/service-dataset-access/api.html#resources:/dataset-end-users/{end-user-id}:get

**Comment by chowington** [comment]
Hi @ryanrdoherty, it looks like a single form property is missing from the above endpoint's response: `priorAuth`. Could you add that last one, please?

**Comment by chowington** [comment]
I quickly looked at the PR, and I notice it does mention the `priorAuth`, however I'm not getting it in the response for some reason.

**Comment by chowington** [comment]
Also (sorry for all the comments :), it seems that hitting this endpoint with an end-user-id that doesn't have an existing request returns a 404. Is that correct?

**Comment by chowington** [comment]
New ticket: https://github.com/VEuPathDB/service-dataset-access/issues/57

**Comment by ryanrdoherty** [comment]
Connor's new ticket was addressed and this issue was already fixed.  Reclosing.
