### ISSUE TITLE
allow same user account to re-request data access after a denial

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/service-dataset-access#64]
https://redmine.apidb.org/issues/51673

check current functionality...If a request from a particular user account is denied, please make sure that the same user account make a future request for the same dataset? 

If this isn't currently possible, please allow the same user account to re-request a study for which they were previously denied. (Sometimes we deny requests, then people work on a better proposal and request again).

**Comment by dmgaldi** [comment]
@danicahelb 

It looks like a user can make a single re-request and then we don't allow edits after that. I'm guessing the intention is to keep people from:
* Spamming e-mails to providers
* Updating requests while folks are in the middle of reviewing
I think if I removed that check, this would work. I could also set it to re-enable edits after a request is denied. Let me know what the preferred behavior is.

**Comment by danicahelb** [comment]
Yeah, i think setting it to re-enable edits after a request is denied sounds good. And keep the single re-request for a study under review. Thanks @dmgaldi

**Comment by nkittur-uga** [comment]
Yes, this worked as intended.
