### ISSUE TITLE
Automatically send requestors an email when the request has been approved or denied

### ISSUE THREAD

**Issue by danicahelb** [VEuPathDB/service-dataset-access#65]
New functionality is needed to automatically send an email to the requestor when they are approved or denied. this should be implemented for restriction levels: 

1. protected-active (ie, study team manually approves or denies each request)
2. protected-passive (ie, auto-approval after XX days, study team can manually deny each request)
3. controlled (ie, access automatically granted after request submission)

We have their user ID as part of their data access request. @dmgaldi indicated it should be possible to look up the e-mail associated with the account.

**The email body for approvals should say:**

`Your request to access [INSERT STUDY NAME <displayName>] data on ClinEpiDB has been approved. Navigate to the "Download" tab of [INSERT STUDY NAME <displayName>] to download the data. Please cite that you accessed data via ClinEpiDB. Thank you!`

**The email body for denials should say:**

`Unfortunately, your request to access [INSERT STUDY NAME <displayName>] data on ClinEpiDB has been denied. Please reach out to [INSERT STUDY MANAGER EMAILS <prop name="requestEmailBcc">] for more information. Thank you!`

**Comment by danicahelb** [comment]
tested this... emails are getting sent for protected studies but not for controlled studies

**Comment by nkittur-uga** [comment]
This failed QA. I 

- equested MAL-ED (using my gmail account) and got an auto-email saying my request has been received
- denied it using my staff account, and **did not get an auto-email about the denial**
- edited and resubmitted my request
- approved it using my staff account
- **did not get an email about the approval**

**Comment by danicahelb** [comment]
Using clinepidb.org, I requested access to Jilinde Costing Study of PrEP in Kenya using my yahoo account (helbda@yahoo.com)

with my staff account (dhelb@sas.upenn.edu), I approved this access request.

I never received an email to my yahoo account that the request was approved.

I then used my staff account to deny the request, and I still received no email to my yahoo account that the request was then denied.

**Comment by danicahelb** [comment]
10/20/2023

This is still failing QA.

The requestor does not receive an email when the request has been approved or denied.

**Comment by dmgaldi** [comment]
In my test environment the emails go through. We may need systems help with this.

**Comment by danicahelb** [comment]
as of 11/15 the requestor does not get an email

**Comment by danicahelb** [comment]
requestors and managers are getting emails now upon approvals and denials.

please make these changes:

**denial email**
- add full request
- cc managers and help@
- update email body:
```
Unfortunately, your request to access Jilinde Costing Study of PrEP in Kenya data on ClinEpiDB has been denied for the following reason: "16 Nov 2023 17:43:20 GMT: Status was changed to Denied.

Reason: testing".

You may resubmit with new information. Please reach out to [danicahelb02@hotmail.com](mailto:danicahelb02@hotmail.com) for more information. Thank you!

Request details:
```

**approval email**
- add full request
- cc managers and help@

**Comment by danicahelb** [comment]
<img width="894" alt="image" src="https://github.com/VEuPathDB/service-dataset-access/assets/25450900/dbfb5b94-0332-4293-98ea-e492c6354e18">

**Comment by danicahelb** [comment]
<img width="920" alt="image" src="https://github.com/VEuPathDB/service-dataset-access/assets/25450900/69ee7a2a-d8c7-439e-a747-9fc9e6b958d2">

**Comment by danicahelb** [comment]
looks good, closing
