### ISSUE TITLE
Verbiage change to denial email, explaining that they can respond to the denial

### ISSUE THREAD

**Issue by aurreco-uga** [VEuPathDB/service-dataset-access#72]
The current email sent to a user who has been denied a request, says 

"Unfortunately, your request to access $dataset.displayName$ data on ClinEpiDB has been denied for the following reason: "$end-user.denialReason$". Please reach out to $dataset.requestEmail$ for more information. Thank you!"

 Given that we agreed that a user will be able to edit content while the approval status is denied,  we should add that they can resend a request anytime.

**Comment by danicahelb** [comment]
as of 9/18/2023, denial emails are not getting sent to the requestor

**Comment by danicahelb** [comment]
as of 10/20/2023 denial emails are not getting sent to the requestor

**Comment by dmgaldi** [comment]
The [code should be doing the right thing here as far as I can tell](https://github.com/VEuPathDB/service-dataset-access/blob/master/src/main/java/org/veupathdb/service/access/service/user/EndUserPatchService.java#L206-L213). I'll test this again myself but we may need systems help if it works again for me but not for Danica.

**Comment by danicahelb** [comment]
<img width="838" alt="image" src="https://github.com/VEuPathDB/service-dataset-access/assets/25450900/6b6ecb88-a3b8-4566-9deb-6b1afb3dd64c">

looks good, closing ticket
