### ISSUE TITLE
ClinEpiDB passive protected studies need date-stamp in user access dashboard after auto-approval

### ISSUE THREAD

**Issue by nkittur-uga** [VEuPathDB/service-dataset-access#80]
For protected passive studies, once user is auto-approved after the waiting period, the system is not adding date-time stamp in “Notes”. Please add that functionality. 

Also, once a user is auto-approved, they are not currently getting a row in **_End Users Table Updates_**. Please make sure that any auto-approved updates are also being logged. The "Who performed action" column can say "auto-approved". 

<img width="1050" alt="Screenshot 2023-09-05 at 11 35 09 AM" src="https://github.com/VEuPathDB/EdaNewIssues/assets/67710160/35f1da7b-d71a-404c-a298-78f5a59eb885">

<img width="1444" alt="image" src="https://github.com/VEuPathDB/EdaNewIssues/assets/25450900/a0801bfc-a8ba-4671-8755-bba86a348103">

**Comment by danicahelb** [comment]
clinepi outreach team is waiting on an auto-approval to come through to check

**Comment by danicahelb** [comment]
@aurreco-uga we checked with Yin Bun on PROVIDE, who was passively given access. No notes were added to the Data Requestor Table updates

<img width="1429" alt="image" src="https://github.com/VEuPathDB/service-dataset-access/assets/25450900/1599ebf0-20d4-4283-9d82-7756c08b00cb">

**Comment by danicahelb** [comment]
this is now working, see request information from connor judge from GEMS1

<img width="1445" alt="image" src="https://github.com/VEuPathDB/service-dataset-access/assets/25450900/1677112b-9f0f-4b59-a4dc-3dce0ed7d50e">
