### ISSUE TITLE
permissions endpoint: use presenters table instead of property table 

### ISSUE THREAD

**Issue by aurreco-uga** [VEuPathDB/service-dataset-access#87]
vb mega study - substudies are  not loaded from th epresenters so they do not have properties...
https://epvb.slack.com/archives/GBDR4LDNC/p1695758153322669

current info is:
  prop.study_access,
  prop.display_name,
  prop.short_display_name,
  prop.description,
  prop.days_for_approval,
  prop.custom_approval_email_body

what I think we shoudl do is for studies without props use the presenters info:
display_name,
short_display_name,
description,

**Comment by ryanrdoherty** [comment]
Resolved by commit [f6426299d71f53e008c33e0b7aa0e742a1ff3fe2](https://github.com/VEuPathDB/service-dataset-access/commit/f6426299d71f53e008c33e0b7aa0e742a1ff3fe2)
